In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))
        
from tensorflow.keras.preprocessing.text import Tokenizer

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
sentences = [
    'Ich habe keine lust',
    'Ich will eure hande sehen',
    'Ich will das ihr mir vertraut',
    'Ich hasse kinder',
    'Ich bin schon langen kallt'
]

In [3]:
tk = Tokenizer(num_words = 200)
tk.fit_on_texts(sentences)
wordindex = tk.word_index
wordindex

{'ich': 1,
 'will': 2,
 'habe': 3,
 'keine': 4,
 'lust': 5,
 'eure': 6,
 'hande': 7,
 'sehen': 8,
 'das': 9,
 'ihr': 10,
 'mir': 11,
 'vertraut': 12,
 'hasse': 13,
 'kinder': 14,
 'bin': 15,
 'schon': 16,
 'langen': 17,
 'kallt': 18}

In [4]:
sequences = tk.texts_to_sequences(sentences)
sequences

[[1, 3, 4, 5],
 [1, 2, 6, 7, 8],
 [1, 2, 9, 10, 11, 12],
 [1, 13, 14],
 [1, 15, 16, 17, 18]]

Testing with unknown sequences to check for tokenization

In [5]:
testsentences = [
    'Ich will eure phantasie',
    'Ich liebe dich',
    'Nein ich hasse lust'
]

In [6]:
testseq = tk.texts_to_sequences(testsentences)
testseq

[[1, 2, 6], [1], [1, 13, 5]]

In [7]:
tk2 = Tokenizer(num_words = 200, oov_token = "{bro idk}")
tk2.fit_on_texts(sentences)
wordindex = tk2.word_index
wordindex

{'{bro idk}': 1,
 'ich': 2,
 'will': 3,
 'habe': 4,
 'keine': 5,
 'lust': 6,
 'eure': 7,
 'hande': 8,
 'sehen': 9,
 'das': 10,
 'ihr': 11,
 'mir': 12,
 'vertraut': 13,
 'hasse': 14,
 'kinder': 15,
 'bin': 16,
 'schon': 17,
 'langen': 18,
 'kallt': 19}

In [8]:
testseq = tk2.texts_to_sequences(testsentences)
testseq

[[2, 3, 7, 1], [2, 1, 1], [1, 2, 14, 6]]

Testing sequences with padding to check if it maintains equal length

In [9]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [10]:
padded = pad_sequences(testseq, maxlen=5)
padded

array([[ 0,  2,  3,  7,  1],
       [ 0,  0,  2,  1,  1],
       [ 0,  1,  2, 14,  6]], dtype=int32)

In [11]:
padded = pad_sequences(testseq, padding='post')
padded

array([[ 2,  3,  7,  1],
       [ 2,  1,  1,  0],
       [ 1,  2, 14,  6]], dtype=int32)

In [12]:
padded = pad_sequences(testseq, maxlen=3, truncating='post')
padded

array([[ 2,  3,  7],
       [ 2,  1,  1],
       [ 1,  2, 14]], dtype=int32)

In [13]:
padded = pad_sequences(testseq, maxlen=3, truncating='pre')
padded

array([[ 3,  7,  1],
       [ 2,  1,  1],
       [ 2, 14,  6]], dtype=int32)

Yes, the lines are in German, yes they are from Rammstein songs. I quite like them